### ISSUE TITLE
Lint Scripts + Pre-Commit Hooks

### ISSUE THREAD

**Issue by JaganKaartik** [JaganKaartik/Foodle#3]
## Todo

- [x] Add Pre-Commit Hook.
- [x] Husky + Lint-Staged. 
- [x] Add Lint and Prettier Scripts
- [x] Test Commit Hooks
